import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import {
  checkVersionConsistency,
  parseCargoLockVersion,
  parseCargoTomlVersion
} from "./versionConsistency.mjs";

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..");

function readRepoFile(relativePath) {
  return readFileSync(join(repoRoot, relativePath), "utf8");
}

const validCargoToml = `[package]
name = "tweakmind"
version = "0.2.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
`;

const validCargoLock = `# This file is automatically @generated by Cargo.
version = 3

[[package]]
name = "serde"
version = "1.0.219"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "tweakmind"
version = "0.2.0"
dependencies = [
 "serde",
]

[[package]]
name = "zerocopy"
version = "0.7.35"
`;

function buildContents(overrides = {}) {
  return {
    packageJson: JSON.stringify({ name: "tweakmind", version: "0.2.0" }),
    tauriConf: JSON.stringify({ productName: "TweakMind", version: "0.2.0" }),
    cargoToml: validCargoToml,
    cargoLock: validCargoLock,
    ...overrides
  };
}

describe("parseCargoTomlVersion", () => {
  it("reads the version from the package section", () => {
    expect(parseCargoTomlVersion(validCargoToml)).toBe("0.2.0");
  });

  it("ignores version-like strings in dependency sections", () => {
    const content = `[package]
name = "tweakmind"
version = "0.2.0"

[dependencies.serde]
version = "1.0.0"
`;
    expect(parseCargoTomlVersion(content)).toBe("0.2.0");
  });

  it("returns null when the package section is missing", () => {
    expect(parseCargoTomlVersion('[dependencies]\nserde = "1"\n')).toBeNull();
  });

  it("returns null for empty content", () => {
    expect(parseCargoTomlVersion("")).toBeNull();
  });
});

describe("parseCargoLockVersion", () => {
  it("finds the tweakmind package among other packages", () => {
    expect(parseCargoLockVersion(validCargoLock)).toBe("0.2.0");
  });

  it("returns null when the package is absent", () => {
    expect(parseCargoLockVersion('[[package]]\nname = "serde"\nversion = "1.0.219"\n')).toBeNull();
  });

  it("does not confuse packages whose names contain tweakmind as a substring", () => {
    const content = `[[package]]
name = "tweakmind-helper"
version = "9.9.9"

[[package]]
name = "tweakmind"
version = "0.2.0"
`;
    expect(parseCargoLockVersion(content)).toBe("0.2.0");
  });

  it("supports looking up a different package name", () => {
    expect(parseCargoLockVersion(validCargoLock, "serde")).toBe("1.0.219");
  });
});

describe("checkVersionConsistency", () => {
  it("passes when all four sources agree", () => {
    const { versions, errors } = checkVersionConsistency(buildContents());

    expect(errors).toEqual([]);
    expect(versions).toEqual({
      "package.json": "0.2.0",
      "src-tauri/tauri.conf.json": "0.2.0",
      "src-tauri/Cargo.toml": "0.2.0",
      "src-tauri/Cargo.lock": "0.2.0"
    });
  });

  it("fails when the lockfile lags behind", () => {
    const { errors } = checkVersionConsistency(
      buildContents({ cargoLock: validCargoLock.replace('version = "0.2.0"', 'version = "0.1.0"') })
    );

    expect(errors).toHaveLength(1);
    expect(errors[0]).toContain("Version mismatch");
    expect(errors[0]).toContain("src-tauri/Cargo.lock=0.1.0");
  });

  it("fails when package.json disagrees", () => {
    const { errors } = checkVersionConsistency(
      buildContents({ packageJson: JSON.stringify({ version: "0.3.0" }) })
    );

    expect(errors).toHaveLength(1);
    expect(errors[0]).toContain("package.json=0.3.0");
  });

  it("reports unreadable sources instead of throwing", () => {
    const { versions, errors } = checkVersionConsistency(buildContents({ tauriConf: "{ not json" }));

    expect(versions["src-tauri/tauri.conf.json"]).toBeNull();
    expect(errors.some((error) => error.includes("src-tauri/tauri.conf.json"))).toBe(true);
  });

  it("reports a missing version field as unreadable", () => {
    const { errors } = checkVersionConsistency(buildContents({ packageJson: JSON.stringify({ name: "tweakmind" }) }));

    expect(errors.some((error) => error.includes("package.json"))).toBe(true);
  });
});

describe("repository release files", () => {
  it("currently declare one consistent tweakmind version", () => {
    const { versions, errors } = checkVersionConsistency({
      packageJson: readRepoFile("package.json"),
      tauriConf: readRepoFile("src-tauri/tauri.conf.json"),
      cargoToml: readRepoFile("src-tauri/Cargo.toml"),
      cargoLock: readRepoFile("src-tauri/Cargo.lock")
    });

    expect(errors).toEqual([]);
    expect(versions["src-tauri/Cargo.lock"]).toBe(versions["package.json"]);
  });

  it("pass the CLI entry point with exit code 0", () => {
    const stdout = execFileSync(process.execPath, [join(repoRoot, "scripts", "check-versions.mjs")], {
      encoding: "utf8"
    });

    expect(stdout).toContain("Version consistency check passed.");
  });
});
